[package]
name = "delegable-derive"
version = "0.3.0"
authors = ["Louis Dureuil <louis.dureuil@xinra.net>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.13.1", features = ["full"] }
quote = "0.5.1"
